fix: staging

diff --git a/docker/Dockerfile.fly b/docker/Dockerfile.fly
--- a/docker/Dockerfile.fly
+++ b/docker/Dockerfile.fly
@@ -1,5 +1,7 @@
 FROM --platform=linux/amd64 node:20-alpine AS base
 
+LABEL fly_launch_runtime="Next.js/Prisma"
+
 FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat openssl
@@ -13,7 +15,13 @@ ENV HUSKY 0
 
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN corepack enable pnpm && pnpm i --frozen-lockfile
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
 
 ##### BUILDER
 
@@ -29,7 +37,13 @@ COPY . .
 ENV NEXT_TELEMETRY_DISABLED 1
 ENV DOCKER_OUTPUT 1
 ENV SKIP_ENV_VALIDATION 1
-RUN corepack enable pnpm && pnpm run build
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 ##### RUNNER
 
@@ -55,6 +69,10 @@ RUN chown nextjs:nodejs .next
 # https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+# copy prisma and migrate script
+COPY --from=builder --chown=nextjs:nodejs /app/scripts/migrate.sh ./scripts/migrate.sh
+COPY --from=builder --chown=nextjs:nodejs /app/prisma ./
 
 USER nextjs
 
